# Generated by Django 2.2.7 on 2019-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20191117_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='key',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
    ]
